// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => const FirebaseOptions(
    apiKey: 'AIzaSyBNgYaAgK5OA0cmbF863xexwlnDETRzkpw',
    appId: '1:453696388011:android:59ab9261a3955099e3f0ee',
    messagingSenderId: '453696388011',
    projectId: 'vista-jklu',
    storageBucket: 'vista-jklu.firebasestorage.app',
  );

  static FirebaseOptions get ios => const FirebaseOptions(
    apiKey: 'AIzaSyA17h8iDBwSvqqptF4mGfOJ5bsosei6qfA',
    appId: '1:453696388011:ios:52e25043e20f7a71e3f0ee',
    messagingSenderId: '453696388011',
    projectId: 'vista-jklu',
    storageBucket: 'vista-jklu.firebasestorage.app',
    iosBundleId: 'com.vista.vistaApp',
  );

  static FirebaseOptions get web => const FirebaseOptions(
    apiKey: 'AIzaSyC89dCMuTOETtpjJbGj2ZvVA6tdvGaxzZY',
    appId: '1:453696388011:web:089e90e69035e8cee3f0ee',
    messagingSenderId: '453696388011',
    projectId: 'vista-jklu',
    authDomain: 'vista-jklu.firebaseapp.com',
    storageBucket: 'vista-jklu.firebasestorage.app',
    measurementId: 'G-F4L0EFZCDS',
  );
}
