# Standard Flutter Podfile for VISTA-APP
platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = '1'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Load the podhelper script. In CI, we manually copy this to ios/Flutter/podhelper.rb
# In local development, it will use the relative path created by Flutter.
require_relative '../Flutter/podhelper'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.expand_path(File.join('..', '..'), __FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Force iOS 15.0 for all plugins to satisfy cloud_firestore
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
